//
//  SelfVerifyScript.swift
//  teemoon
//
//  Generates a self-contained python script the user can copy and run on
//  their own machine to re-verify this session independently. The session's
//  attested values (signing addresses, compose hashes, E2EE key) are embedded
//  as constants; the script fetches FRESH attestations with its own nonces —
//  from BOTH the gateway and the model's direct host when the session has
//  both, since each attests different identities (gateway TEE vs GPU node) —
//  re-runs the checks near.ai documents (docs.near.ai/cloud/verification)
//  using python3 stdlib only, and compares the live service against what the
//  session saw. `--full` clones near.ai's open-source verifier for the deep
//  suite (dcap-qvl, NRAS, report_data bindings, chat-signature ecrecover,
//  and the E2EE chat path teemoon actually uses) —
//  we deliberately delegate those to near.ai's maintained reference
//  implementation rather than re-implementing them in a generated script.
//
//  No secrets are ever embedded: the attestation endpoints are public, and
//  the chat verifier reads the user's API key from their environment.
//  Pure string generation — testable without SwiftUI.
//

import Foundation

extension AttestationSummary {

    /// The copyable self-verification block, or nil before an attestation
    /// record exists. Deterministic for a given record (timestamps come from
    /// the record's own `fetchedAt`, never "now").
    ///
    /// Shaped to paste straight into a terminal: a shell heredoc writes
    /// `teemoon_verify.py` to disk, then runs the quick checks. Writing the
    /// file (rather than piping code into an interpreter) leaves the user an
    /// inspectable artifact they can review and re-run with `--full`.
    var selfVerifyScript: String? {
        guard let att = attestation, let provider else { return nil }

        func py(_ value: String?) -> String {
            guard let value, !value.isEmpty else { return "None" }
            // These values are decoded straight from the remote service's
            // attestation JSON — the very party this script lets the user
            // check. Control characters must never reach the output: a raw
            // newline could close the shell heredoc early (a line equal to
            // the delimiter would execute everything after it as shell) or
            // break the python string literal. Escape them all, not just
            // quotes and backslashes.
            var escaped = ""
            for scalar in value.unicodeScalars {
                switch scalar {
                case "\\": escaped += "\\\\"
                case "\"": escaped += "\\\""
                case "\n": escaped += "\\n"
                case "\r": escaped += "\\r"
                case "\t": escaped += "\\t"
                default:
                    if scalar.value < 0x20 || scalar.value == 0x7f {
                        escaped += String(format: "\\x%02x", scalar.value)
                    } else {
                        escaped.unicodeScalars.append(scalar)
                    }
                }
            }
            return "\"\(escaped)\""
        }

        let capturedAt = ISO8601DateFormatter().string(from: att.fetchedAt)
        let gatewayBase = provider.openAIBaseURL?.absoluteString
        let directBase = provider.directGPUNodeURL?.absoluteString

        let python = #"""
        #!/usr/bin/env python3
        """teemoon self-verification

        generated by teemoon from your live session — the values under SESSION are
        what your device saw, cryptographically. this script re-runs near.ai's
        documented verification (https://docs.near.ai/cloud/verification) against
        fresh data and compares it with your session.

        usage:
          python3 teemoon_verify.py          # quick checks — python3 stdlib only
          python3 teemoon_verify.py --full   # also clone near.ai's open-source
                                             # verifier and run the complete documented
                                             # suite: dcap-qvl TDX quote verification,
                                             # NVIDIA NRAS, report_data bindings,
                                             # chat signature ecrecover, E2EE chat

        set NEARAI_CLOUD_API_KEY (or API_KEY) to your normal inference API key for
        the GATEWAY's own attestation and for --full chat verification:
        cloud-api.near.ai answers /attestation/report only to an authenticated
        caller ("Missing authorization header" otherwise). The model host answers
        anyone, so the checks that matter most still run without a key. The key is
        read from the environment and sent to near.ai only — never written into
        this file, never sent anywhere else.
        """

        SESSION = {
            # captured from your teemoon session
            "captured_at":             \#(py(capturedAt)),
            "model":                   \#(py(provider.model)),
            "gateway_base":            \#(py(gatewayBase)),
            "direct_base":             \#(py(directBase)),
            "gateway_signing_address": \#(py(att.signingAddress)),
            "gpu_signing_address":     \#(py(att.gpuSigningAddress)),
            "compose_hash":            \#(py(att.composeHash)),
            "gpu_node_compose_hash":   \#(py(att.gpuNodeComposeHash)),
            "model_ed25519_pubkey":    \#(py(att.modelEd25519PubKey?.hexString)),
            "mrtd":                    \#(py(att.mrtd)),
            "os_image_hash":           \#(py(att.osImageHash)),
        }

        import hashlib
        import json
        import os
        import re
        import secrets
        import shutil
        import subprocess
        import sys
        import tempfile
        import urllib.error
        import urllib.parse
        import urllib.request

        GREEN, RED, YELLOW, DIM, BOLD, RESET = "\033[32m", "\033[31m", "\033[33m", "\033[2m", "\033[1m", "\033[0m"
        counts = {"passed": 0, "failed": 0, "skipped": 0, "warned": 0}

        def _tally(kind, prefix, suffix=""):
            def report(msg):
                counts[kind] += 1
                print(f"  {prefix} {msg}{suffix}")
            return report

        ok   = _tally("passed",  f"{GREEN}✓{RESET}")
        bad  = _tally("failed",  f"{RED}✗{RESET}")
        skip = _tally("skipped", f"{DIM}−", RESET)
        # expected drift (e.g. a legitimate redeploy) — never fails the run
        warn = _tally("warned",  f"{YELLOW}~{RESET}")

        def section(title):
            print(f"\n{BOLD}{title}{RESET}")

        # Same key teemoon itself sends. Read from the environment so this file
        # stays safe to paste anywhere.
        API_KEY = os.environ.get("NEARAI_CLOUD_API_KEY") or os.environ.get("API_KEY") or ""

        def fetch_json(url, api_key=None):
            headers = {"accept": "application/json"}
            if api_key:
                headers["authorization"] = f"Bearer {api_key}"
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=60) as resp:
                return json.loads(resp.read())

        def find_all(obj, key):
            """Collect every value of `key` anywhere in a nested JSON structure."""
            out = []
            if isinstance(obj, dict):
                for k, v in obj.items():
                    if k == key:
                        out.append(v)
                    out.extend(find_all(v, key))
            elif isinstance(obj, list):
                for v in obj:
                    out.extend(find_all(v, key))
            return out

        def fetch_report(base, algo="ecdsa", extra="", api_key=None):
            """Fetch an attestation report with a fresh nonce; returns (report, nonce)."""
            nonce = secrets.token_hex(32)
            return fetch_json(f"{base}/attestation/report?signing_algo={algo}"
                              f"&nonce={nonce}{extra}", api_key), nonce

        def main():
            print(f"{BOLD}teemoon self-verification{RESET}")
            print(f"{DIM}session captured {SESSION['captured_at']} · model {SESSION['model']}{RESET}")

            # ---- 1. fresh attestations, independent of the app ---------------------
            # the gateway and the model's direct host each attest different things
            # (gateway TEE vs GPU node TEE), so fetch both when the session has both.
            section("1. fresh attestations (this machine, fresh nonces — not the app's data)")
            model_q = urllib.parse.quote(SESSION["model"], safe="")
            reports = []
            # Labels whose live evidence we could NOT obtain. Section 2 compares
            # your session against what is fetched here, so anything missing has
            # to disable the comparisons that depend on it — see there.
            missing = []
            for label, base, extra, key in (
                    ("gateway", SESSION["gateway_base"], f"&model={model_q}", API_KEY),
                    ("model host", SESSION["direct_base"], "", None)):
                if not base:
                    continue
                try:
                    r, n = fetch_report(base, extra=extra, api_key=key)
                    reports.append((label, r, n))
                    ok(f"{label} report fetched from {base}")
                except urllib.error.HTTPError as e:
                    missing.append(label)
                    if e.code in (401, 403) and not key:
                        skip(f"{label} report needs your API key — export "
                             f"NEARAI_CLOUD_API_KEY (the same inference key teemoon "
                             f"sends) and re-run to check it")
                    else:
                        bad(f"could not fetch {label} report: {e}")
                except Exception as e:
                    missing.append(label)
                    bad(f"could not fetch {label} report: {e}")
            if not reports:
                return finish()
            for label, r, n in reports:
                if n in json.dumps(r):
                    ok(f"{label} echoed this run's fresh nonce (quote-level echo proven in --full)")
                else:
                    bad(f"fresh nonce missing from the {label} report — possible replay or API change")

            # ---- 2. does the live service match your session? ----------------------
            # gateway identities only appear in the gateway report and node
            # identities only on the host that serves them, so compare against
            # the merged evidence from every report.
            section("2. live service vs. your session")
            live_addresses = {a.lower() for _, r, _ in reports
                              for a in find_all(r, "signing_address") if isinstance(a, str)}
            live_compose = {h.lower() for _, r, _ in reports
                            for h in find_all(r, "compose_hash") if isinstance(h, str)}
            gateway_key_ok = False

            for label, addr, h in (
                    ("gateway", SESSION["gateway_signing_address"], SESSION["compose_hash"]),
                    ("gpu node", SESSION["gpu_signing_address"], SESSION["gpu_node_compose_hash"])):
                # A signing key is sealed inside the TEE; an attacker swapping code
                # cannot reproduce it. So "same key, different compose hash" is the
                # signature of a legitimate redeploy, whereas a changed key is
                # genuinely suspicious.
                #
                # ABSENT EVIDENCE IS NOT CONTRARY EVIDENCE. A report that could not
                # be fetched at all (no API key for the gateway, network down)
                # leaves its identities out of the live sets below — and reading
                # that absence as "changed" printed "code identity AND signing key
                # both changed — treat with suspicion" at a service that had done
                # nothing. Anything not found while a report is missing is
                # UNCHECKED, and says so.
                unchecked = bool(missing)
                key_ok = bool(addr) and addr.lower() in live_addresses
                if label == "gateway":
                    gateway_key_ok = key_ok
                if key_ok:
                    ok(f"{label} signing key is the one your session verified ({addr[:10]}…)")
                elif addr and unchecked:
                    skip(f"{label} signing key not checked — the {' and '.join(missing)} "
                         f"report above could not be fetched, so there is nothing to "
                         f"compare your session's {addr[:10]}… against")
                elif addr:
                    bad(f"{label} signing key changed since your session — the service may "
                        f"have legitimately redeployed, but your session attested {addr[:10]}…")
                if not h:
                    continue
                if h.lower() in live_compose:
                    ok(f"{label} runs the same code identity (compose hash) your session verified")
                elif key_ok:
                    warn(f"{label} code identity (compose hash) changed since your session, but its "
                         f"signing key is unchanged — a legitimate redeploy. Re-run with --full to "
                         f"verify the new code against near.ai's provenance. Session attested {h[:12]}…")
                elif unchecked:
                    skip(f"{label} code identity (compose hash) not checked — no live "
                         f"report to compare {h[:12]}… against")
                else:
                    bad(f"{label} code identity (compose hash) AND signing key both changed since "
                        f"your session — unexpected; treat with suspicion. Session attested {h[:12]}…")

            # ---- the machine underneath the containers -------------------------
            # MRTD is the Intel TDX measurement of the gateway enclave itself and
            # os_image_hash the guest image it booted — one level BELOW the compose
            # hash, which only says which containers run inside. Your session
            # recorded both; they are worth exactly as much as any other identity
            # here, and until 2026-08-23 this script embedded them under SESSION
            # and never looked at them again.
            #
            # Compared against the GATEWAY's own report, not the merged set: the
            # model node reports its own os_image_hash, and matching yours against
            # a different machine's image would be a check that cannot fail.
            gateway_report = next((r for label, r, _ in reports if label == "gateway"), None)
            for field, what in (("mrtd", "gateway TDX measurement (MRTD)"),
                                ("os_image_hash", "gateway guest OS image")):
                want = SESSION[field]
                if not want:
                    continue
                if gateway_report is None:
                    skip(f"{what} not checked — no gateway report to compare "
                         f"{want[:12]}… against")
                    continue
                live = {v.lower() for v in find_all(gateway_report, field)
                        if isinstance(v, str)}
                if want.lower() in live:
                    ok(f"{what} is the one your session verified ({want[:12]}…)")
                elif gateway_key_ok:
                    warn(f"{what} changed since your session, but the gateway's signing "
                         f"key is unchanged — a legitimate redeploy onto a new image. "
                         f"Session attested {want[:12]}…")
                else:
                    bad(f"{what} AND the gateway signing key both changed since your "
                        f"session — unexpected; treat with suspicion. Session attested "
                        f"{want[:12]}…")

            if SESSION["model_ed25519_pubkey"]:
                key = SESSION["model_ed25519_pubkey"].lower()
                found = None
                for base, extra, akey in ((SESSION["direct_base"], "", None),
                                          (SESSION["gateway_base"], f"&model={model_q}", API_KEY)):
                    if not base:
                        continue
                    try:
                        found = key in json.dumps(
                            fetch_report(base, "ed25519", extra, akey)[0]).lower()
                        if found:
                            break
                    except Exception:
                        continue
                if found is True:
                    ok("model's E2EE public key is the one your session encrypted to")
                elif found is False:
                    bad("model's E2EE public key changed since your session (redeploys "
                        "rotate keys legitimately)")
                else:
                    skip("could not fetch an ed25519 attestation to check the E2EE key")

            # the model name is self-reported from inside the attested enclave
            # (docs: TLS page, "Verify Model Name") — it should be the model
            # your session was talking to.
            live_models = {m for _, r, _ in reports
                           for m in find_all(r, "model_name") if isinstance(m, str)}
            if not live_models:
                skip("no report self-reports a model name (older proxy version)")
            elif SESSION["model"] in live_models:
                ok(f"TEE self-reports the model your session used ({SESSION['model']})")
            else:
                bad(f"TEE self-reports {sorted(live_models)} — your session used "
                    f"{SESSION['model']}")

            # ---- 3. manifest integrity ---------------------------------------------
            # each report's manifests must hash to a compose_hash attested in that
            # same report.
            section("3. manifest integrity — sha256(docker compose) == attested compose_hash")
            verified_manifests = []
            any_manifest = False
            for label, r, _ in reports:
                manifests = [m for m in find_all(r, "app_compose") + find_all(r, "compose")
                             if isinstance(m, str) and m.strip()]
                if not manifests:
                    continue
                any_manifest = True
                own_hashes = {h.lower() for h in find_all(r, "compose_hash") if isinstance(h, str)}
                matched = [m for m in manifests
                           if hashlib.sha256(m.encode()).hexdigest() in own_hashes]
                if matched:
                    verified_manifests.extend(matched)
                    ok(f"{label}: manifest hashes to its attested compose_hash")
                else:
                    bad(f"{label}: no manifest hashes to its attested compose_hash")
            if not any_manifest:
                skip("no report includes a compose manifest to hash")

            # ---- 3b. inference layer -------------------------------------------------
            # the compose-manager's action log pins the model YAML to a public
            # repo path + commit + hash; fetch it and check the hash matches.
            section("3b. inference layer — model YAML matches the attested hash")
            direct_report = next((r for label, r, _ in reports if label == "model host"), {})
            ups = [a for acts in find_all(direct_report, "actions") if isinstance(acts, list)
                   for a in acts if isinstance(a, dict) and a.get("action") == "compose_up"]
            up = ups[-1] if ups else {}
            path, commit, sha = up.get("file"), up.get("commit"), up.get("file_sha256")
            if not (path and commit and sha):
                skip("no compose_up action pinning the model YAML in the attestation")
            else:
                try:
                    url = f"https://raw.githubusercontent.com/nearai/cvm-compose-files/{commit}/{path}"
                    with urllib.request.urlopen(urllib.request.Request(url), timeout=60) as resp:
                        content = resp.read()
                    digest = hashlib.sha256(content).hexdigest()
                    if digest == sha.lower():
                        verified_manifests.append(content.decode())
                        ok(f"model YAML {path} @ {commit[:7]} matches attested hash")
                    else:
                        bad(f"model YAML at attested commit does NOT match attested hash "
                            f"(attested {sha[:12]}…, got {digest[:12]}…)")
                except Exception as e:
                    skip(f"could not fetch model YAML from public repo: {e}")

            # ---- 4. image provenance — signed build records -------------------------
            # the same check the app runs: every near.ai image in a verified
            # manifest must have a GitHub build attestation published for its
            # exact digest. GitHub's API answers definitively — 404 means no
            # build record exists for that digest, anywhere in that repo.
            section("4. image provenance — signed build records for the exact image digests")
            REPO_ALIASES = {"compose-manager-launcher": "compose-manager",
                            "vllm-proxy-rs": "inference-proxy"}

            def nearai_repo(image):
                """nearai/nearaidev images -> the GitHub repo publishing their
                attestations; None for third-party images (their provenance is
                their publisher's, not near.ai's)."""
                parts = image.split("/")
                if parts and ("." in parts[0] or ":" in parts[0]):
                    parts = parts[1:]  # strip registry host
                if len(parts) < 2 or parts[0].lower() not in ("nearai", "nearaidev"):
                    return None
                name = parts[-1].split(":")[0]
                return "nearai/" + REPO_ALIASES.get(name, name)

            refs = sorted({(i, d) for m in verified_manifests
                           for i, d in re.findall(r"([A-Za-z0-9._/:-]+)@sha256:([0-9a-f]{64})", m)})
            if not refs:
                skip("no image digests to check (no verified manifest)")
            checked = 0
            for image, d in refs:
                repo = nearai_repo(image)
                name = image.split("/")[-1].split(":")[0]
                if repo is None:
                    skip(f"{name}@{d[:12]}…: third-party base image — provenance "
                         f"is its publisher's, not near.ai's")
                    continue
                url = f"https://api.github.com/repos/{repo}/attestations/sha256:{d}"
                try:
                    req = urllib.request.Request(url, headers={
                        "accept": "application/vnd.github+json",
                        "x-github-api-version": "2022-11-28"})
                    with urllib.request.urlopen(req, timeout=30) as resp:
                        status = resp.status
                except urllib.error.HTTPError as e:
                    status = e.code
                except Exception:
                    status = None
                if status == 200:
                    checked += 1
                    ok(f"{name}@{d[:12]}… has a build attestation on {repo}")
                elif status == 404:
                    bad(f"{name}@{d[:12]}… has NO build attestation on {repo} — "
                        f"GitHub answered definitively")
                else:
                    skip(f"{name}@{d[:12]}…: GitHub attestations API unavailable "
                         f"(HTTP {status}, likely rate limit) — no evidence either way")
            if refs and checked == 0 and not any(nearai_repo(i) for i, _ in refs):
                # mirrors the app: a manifest with no near.ai images at all is
                # not something this check can vouch for.
                bad("no near.ai images in the verified manifests — nothing to "
                    "pin provenance to")

            # ---- 5. tls binding ------------------------------------------------------
            section("5. TLS binding — your HTTPS connection ends inside the enclave")
            if not SESSION["direct_base"]:
                skip("session used the gateway path; TLS attestation applies to direct "
                     "completions hosts")
            else:
                try:
                    from cryptography import x509
                    from cryptography.hazmat.primitives import serialization
                    import http.client, ssl
                    host = urllib.parse.urlparse(SESSION["direct_base"]).hostname
                    ctx = ssl.create_default_context()
                    # the TEE's TLS key is self-generated, not CA-signed; trust comes
                    # from the hardware attestation we fetch over this same connection
                    ctx.check_hostname = False
                    ctx.verify_mode = ssl.CERT_NONE
                    conn = http.client.HTTPSConnection(host, 443, context=ctx, timeout=60)
                    conn.connect()
                    cert_der = conn.sock.getpeercert(binary_form=True)
                    cert = x509.load_der_x509_certificate(cert_der)
                    spki = cert.public_key().public_bytes(
                        encoding=serialization.Encoding.DER,
                        format=serialization.PublicFormat.SubjectPublicKeyInfo)
                    live_spki = hashlib.sha256(spki).hexdigest()
                    tls_nonce = secrets.token_hex(32)
                    conn.request("GET", f"/v1/attestation/report?include_tls_fingerprint=true"
                                        f"&signing_algo=ecdsa&nonce={tls_nonce}",
                                 headers={"Host": host, "accept": "application/json"})
                    resp = conn.getresponse()
                    tls_report = json.loads(resp.read())
                    conn.close()
                    attested = [f for f in find_all(tls_report, "tls_cert_fingerprint")
                                if isinstance(f, str)]
                    if not attested:
                        skip("host did not return a tls_cert_fingerprint")
                    elif live_spki in {f.lower().removeprefix("0x") for f in attested}:
                        ok("live TLS key (same connection) matches the attested fingerprint")
                    else:
                        bad("live TLS key does NOT match the attested fingerprint")
                except ImportError:
                    skip("pip install cryptography to run the TLS check here "
                         "(--full also covers it)")
                except Exception as e:
                    bad(f"TLS check errored: {e}")

            # ---- 6. full documented suite --------------------------------------------
            section("6. full documented suite — dcap-qvl · NRAS · report_data · chat + E2EE signatures")
            if "--full" in sys.argv:
                run_full_suite()
            else:
                # after a paste-and-run, retyping the command just to add
                # --full is a chore (the shell history holds the whole paste),
                # so offer to continue right here when a human is attached.
                wants_full = False
                if sys.stdin.isatty():
                    try:
                        wants_full = input(
                            f"  {BOLD}run the full suite now? [y/N]{RESET} "
                        ).strip().lower() in ("y", "yes")
                    except (EOFError, KeyboardInterrupt):
                        print()
                if wants_full:
                    run_full_suite()
                else:
                    skip("re-run with --full to clone near.ai's open-source verifier "
                         "and run the complete suite (needs git + pip)")

            return finish()

        def run_full_suite():
            if not (shutil.which("git") and shutil.which("python3")):
                bad("--full needs git and python3 on PATH")
                return
            workdir = tempfile.mkdtemp(prefix="nearai-verifier-")
            repo = os.path.join(workdir, "nearai-cloud-verifier")
            venv = os.path.join(workdir, "venv")
            vpy = os.path.join(venv, "bin", "python3")
            print(f"  {DIM}cloning near.ai's verifier into {workdir} + installing deps…{RESET}")
            try:
                for step in (["git", "clone", "--depth", "1",
                              "https://github.com/nearai/nearai-cloud-verifier", repo],
                             [sys.executable, "-m", "venv", venv],
                             [vpy, "-m", "pip", "install", "-q", "-r",
                              os.path.join(repo, "requirements.txt")]):
                    subprocess.run(step, check=True, capture_output=True)
            except subprocess.CalledProcessError as e:
                bad(f"could not set up near.ai's verifier: {e}")
                return

            env = dict(os.environ)
            api_key = env.get("NEARAI_CLOUD_API_KEY") or env.get("API_KEY")
            if api_key:
                env["API_KEY"] = api_key
            if SESSION["direct_base"]:
                # near.ai's cloned verifiers append their own `/v1` (e.g.
                # `{BASE_URL}/v1/chat/completions`), whereas our SESSION bases carry
                # the `/v1` our own quick checks need. Hand the verifiers the bare
                # host so the paths don't double up (…/v1/v1/… → upstream 404).
                env.setdefault("BASE_URL", SESSION["direct_base"].removesuffix("/v1"))

            def run_verifier(script, args, label, extra_env=None, retries=0):
                path = os.path.join(repo, "py", script)
                if not os.path.exists(path):
                    skip(f"{label}: {script} not in the verifier repo (layout changed?)")
                    return
                for attempt in range(retries + 1):
                    r = subprocess.run([vpy, path] + args, env={**env, **(extra_env or {})},
                                       cwd=repo, capture_output=True, text=True)
                    sys.stdout.write(r.stdout)
                    sys.stderr.write(r.stderr)
                    if r.returncode == 0:
                        ok(f"{label} passed (near.ai {script})")
                        return
                    # a model is served by several TEE nodes and the signature is
                    # cached only on the node that served the chat, so a lookup can
                    # land elsewhere. near.ai documents this as transient: "simply
                    # retry until you hit the right one."
                    transient = "not found or expired" in (r.stdout + r.stderr)
                    if transient and attempt < retries:
                        print(f"  {DIM}signature lookup landed on a node that didn't serve "
                              f"the chat — documented transient; retrying…{RESET}")
                        continue
                    if transient:
                        warn(f"{label}: signature lookup kept landing on other nodes — a "
                             f"documented near.ai transient, not a failed signature; "
                             f"re-run --full to retry")
                    else:
                        bad(f"{label} FAILED (near.ai {script})")
                    return

            run_verifier("model_verifier.py", ["--model", SESSION["model"]],
                         "model + gateway attestation (dcap-qvl, NRAS, report_data, mr_config)")
            if SESSION["direct_base"]:
                run_verifier("tls_verifier.py", ["--url", SESSION["direct_base"]],
                             "TLS attestation (report_data cert binding)")
            if api_key:
                run_verifier("chat_verifier.py", ["--model", SESSION["model"]],
                             "chat signatures (request/response hash + ecrecover)", retries=2)
                if SESSION["model_ed25519_pubkey"] and SESSION["gateway_base"]:
                    # teemoon's own completions are E2EE via the gateway — this
                    # exercises that exact path, so BASE_URL must be the gateway
                    # even when the session also has a direct host.
                    run_verifier("encrypted_chat_verifier.py",
                                 ["--model", SESSION["model"]],
                                 "E2EE chat (the encrypted path teemoon actually uses)",
                                 extra_env={"BASE_URL":
                                            SESSION["gateway_base"].removesuffix("/v1")})
            else:
                skip("chat + E2EE signature verification needs NEARAI_CLOUD_API_KEY "
                     "(your normal inference key) — each makes one small live chat request")

        def finish():
            section("summary")
            failed, warned = counts["failed"], counts["warned"]
            verdict = (f"{RED}{failed} check(s) failed{RESET}" if failed else
                       f"{YELLOW}{warned} change(s) to re-verify — nothing failed{RESET}" if warned else
                       f"{GREEN}everything checked out{RESET}")
            changed = f" · {warned} changed" if warned else ""
            print(f"  {counts['passed']} passed · {failed} failed{changed} · "
                  f"{counts['skipped']} skipped — {verdict}")
            if warned and not failed:
                print(f"  {DIM}‘changed’ = the service redeployed since your session but its keys are "
                      f"intact (expected). Re-run with --full to verify the new code.{RESET}")
            if failed:
                print(f"  {DIM}a mismatch against your session usually means near.ai "
                      f"redeployed since; a hash or binding failure is more serious.{RESET}")
            return 1 if failed else 0

        if __name__ == "__main__":
            sys.exit(main())
        """#

        // Pure executable shell only — no leading `#` comment lines. Interactive
        // zsh does not honor `#` as a comment (interactive_comments is off by
        // default), so a pasted comment line runs as a command ("command not
        // found: #", or a glob error on any parenthesised text). The script is
        // self-documenting: its docstring explains usage, and the quick run
        // prints the `--full` hint itself.
        return """
        cat > teemoon_verify.py <<'TEEMOON_VERIFY'
        \(python)
        TEEMOON_VERIFY
        python3 teemoon_verify.py
        """
    }
}
